### ISSUE TITLE
Domain and hosting

### ISSUE THREAD

**Issue by DNature** [DNature/team-superusers#5]
Please does anyone have an idea on where to host our app. We also need a domain ASA.

**Comment by yerimaisaac** [comment]
Yeah we can use bluehost or Wiz.com to host

**Comment by DNature** [comment]
I learnt that there is a digitalocean coupon for all naijahacks participant. Smis it still available?

**Comment by yerimaisaac** [comment]
Yeah here is the link do.co/studenthackathon

**Comment by DNature** [comment]
Thanks for the link. it's a $50 coupon. How about the domain with **.xyz** extension, how to we get it or we could use some other free domain from https://freenom.tk  but mostly they're .tk, .ml, .ga extensions.
@yerimaisaac

**Comment by yerimaisaac** [comment]
I was able to register .XYZ but it was showing me a fraud error. 
Plz just go through it

**Comment by yerimaisaac** [comment]
I Have set the digital ocean account good to go now

**Comment by DNature** [comment]
What about the credentials... **email** and **password**
